// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using elearning.ContentService.Infrastructure.Persistence;

#nullable disable

namespace elearning.ContentService.Infrastructure.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260727081754_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LearningPathId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("LevelId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.LearningPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TargetLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetLevelId");

                    b.ToTable("LearningPaths", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParentId");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Grammar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("StructureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Grammars", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.GrammarExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioMediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrammarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AudioMediaId");

                    b.HasIndex("GrammarId");

                    b.ToTable("GrammarExamples", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.GrammarTag", b =>
                {
                    b.Property<Guid>("GrammarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("GrammarId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GrammarTags", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioMediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Radical")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SinoVietnamese")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeOrderJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AudioMediaId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Vocabularies", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.VocabularyExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AudioMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AudioMediaId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("VocabularyExamples", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.VocabularyTag", b =>
                {
                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("VocabularyId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VocabularyTags", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlockType")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ContentPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonBlocks", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonGrammar", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrammarId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "GrammarId");

                    b.HasIndex("GrammarId");

                    b.ToTable("LessonGrammars", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonVocabulary", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "VocabularyId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("LessonVocabularies", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.CourseTag", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CourseTags", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Code")
                        .IsUnique();

                    b.ToTable("Levels", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.PartOfSpeech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("PartsOfSpeech", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Media.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PassScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.AssessmentQuestionSet", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScoreWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssessmentId", "QuestionSetId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("AssessmentQuestionSets", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Explanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Explanations", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("QuestionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SharedContent")
                        .HasColumnType("text");

                    b.Property<Guid?>("SharedMediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.HasIndex("SharedMediaId");

                    b.ToTable("QuestionGroups", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SkillType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("QuestionSets", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Course", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Courses.LearningPath", "LearningPath")
                        .WithMany("Courses")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.LearningPath", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Level", "TargetLevel")
                        .WithMany("LearningPaths")
                        .HasForeignKey("TargetLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetLevel");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Unit", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Courses.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Courses.Unit", "Parent")
                        .WithMany("SubUnits")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Grammar", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Language", "Language")
                        .WithMany("Grammars")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Level", "Level")
                        .WithMany("Grammars")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.GrammarExample", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Media.MediaAsset", "AudioMedia")
                        .WithMany()
                        .HasForeignKey("AudioMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Grammar", "Grammar")
                        .WithMany("Examples")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioMedia");

                    b.Navigation("Grammar");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.GrammarTag", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Grammar", "Grammar")
                        .WithMany("GrammarTags")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Tag", "Tag")
                        .WithMany("GrammarTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Media.MediaAsset", "AudioMedia")
                        .WithMany()
                        .HasForeignKey("AudioMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Language", "Language")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Level", "Level")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AudioMedia");

                    b.Navigation("Language");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.VocabularyExample", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Media.MediaAsset", "AudioMedia")
                        .WithMany()
                        .HasForeignKey("AudioMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioMedia");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.VocabularyTag", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Tag", "Tag")
                        .WithMany("VocabularyTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyTags")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Courses.Unit", "Unit")
                        .WithMany("Lessons")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonBlock", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Lessons.Lesson", "Lesson")
                        .WithMany("LessonBlocks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonGrammar", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Grammar", "Grammar")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Lessons.Lesson", "Lesson")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.LessonVocabulary", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Lessons.Lesson", "Lesson")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", "Vocabulary")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.CourseTag", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Courses.Course", "Course")
                        .WithMany("CourseTags")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Tag", "Tag")
                        .WithMany("CourseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Level", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Language", "Language")
                        .WithMany("Levels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.AssessmentQuestionSet", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Questions.Assessment", "Assessment")
                        .WithMany("AssessmentQuestionSets")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Questions.QuestionSet", "QuestionSet")
                        .WithMany("AssessmentQuestionSets")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Explanation", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Media.MediaAsset", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.Questions.Question", "Question")
                        .WithMany("Explanations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Option", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Questions.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Question", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Questions.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("elearning.ContentService.Domain.Questions.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionGroup", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Questions.QuestionSet", "QuestionSet")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.Media.MediaAsset", "SharedMedia")
                        .WithMany()
                        .HasForeignKey("SharedMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QuestionSet");

                    b.Navigation("SharedMedia");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionSet", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Level", "Level")
                        .WithMany("QuestionSets")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Level");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionTag", b =>
                {
                    b.HasOne("elearning.ContentService.Domain.Questions.Question", "Question")
                        .WithMany("QuestionTags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("elearning.ContentService.Domain.MasterData.Entities.Tag", "Tag")
                        .WithMany("QuestionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Course", b =>
                {
                    b.Navigation("CourseTags");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.LearningPath", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Courses.Unit", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("SubUnits");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Grammar", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("GrammarTags");

                    b.Navigation("LessonGrammars");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Knowledge.Entities.Vocabulary", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("LessonVocabularies");

                    b.Navigation("VocabularyTags");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Lessons.Lesson", b =>
                {
                    b.Navigation("LessonBlocks");

                    b.Navigation("LessonGrammars");

                    b.Navigation("LessonVocabularies");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Language", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("Levels");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Level", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Grammars");

                    b.Navigation("LearningPaths");

                    b.Navigation("QuestionSets");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.MasterData.Entities.Tag", b =>
                {
                    b.Navigation("CourseTags");

                    b.Navigation("GrammarTags");

                    b.Navigation("QuestionTags");

                    b.Navigation("VocabularyTags");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Assessment", b =>
                {
                    b.Navigation("AssessmentQuestionSets");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.Question", b =>
                {
                    b.Navigation("Explanations");

                    b.Navigation("Options");

                    b.Navigation("QuestionTags");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("elearning.ContentService.Domain.Questions.QuestionSet", b =>
                {
                    b.Navigation("AssessmentQuestionSets");

                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
